[package]
name = "hyprland-scratchpad"
version = "0.1.0"
edition = "2021"

[dependencies]
hyprland = { git = "https://github.com/hyprland-community/hyprland-rs.git", rev="0.4.0-alpha.2" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"